New Week 2
pesto-students/p13-nishant-naithani-Rajeev2k11 pull request #4
Opened 2023-08-14 10:52 UTC by Rajeev2k11

Assignment -1  from week-2 completed

2023-08-31 06:44 UTC, NishantNaithani requested changes

2023-08-31 06:44 UTC, NishantNaithani commented on Week-2/Assignment-1/ques-3.html
Here,
Default value is not defined

2023-08-31 06:45 UTC, NishantNaithani commented
Hey @Rajeev2k11 ,
Added comments

2023-09-01 12:42 UTC, Rajeev2k11 commented on Week-2/Assignment-1/ques-3.html
Which default value? I could not get it.

2023-09-01 13:01 UTC, NishantNaithani commented on Week-2/Assignment-1/ques-3.html
<img width="671" alt="Screenshot 2023-09-01 at 6 29 55 PM" src="https://github.com/pesto-students/p13-nishant-naithani-Rajeev2k11/assets/30075028/d7c3ebf4-38de-4225-af93-1f23110cc179">

2023-09-18 08:52 UTC, merged