Week 3
pesto-students/p13-nishant-naithani-Rajeev2k11 pull request #5
Opened 2023-08-25 12:08 UTC by Rajeev2k11

Week 3 assignmnet

2023-09-14 17:25 UTC, NishantNaithani requested changes

2023-09-14 17:25 UTC, NishantNaithani commented on Week-3/JS Scopes, Global Object & Context/Assignment-1.js
Here,
Use this method to calculate the power `return Math.pow(num1, exp);`

2023-09-14 17:25 UTC, NishantNaithani commented on Week-3/Javascript Fundamentals/assignment-1.js
Here,
`.map` is used for iterating and creating a purely new array with modifications, you should use `.forEach` for these types of operations where you just need to iterate the array and update other variables

2023-09-18 08:48 UTC, Rajeev2k11 commented on Week-3/JS Scopes, Global Object & Context/Assignment-1.js
done

2023-09-18 08:52 UTC, Rajeev2k11 commented on Week-3/Javascript Fundamentals/assignment-1.js
done

2023-09-18 08:52 UTC, merged